import { MapDocument } from '../modules/application/l1/l2/l3/map/documents/MapStructures';
import { MapCurrent } from '../modules/application/l1/l2/l3/map/mapCurrent/MapCurrent';
import { MapCurrentID } from '../modules/application/l1/l2/l3/map/mapCurrent/MapCurrentID';
import { MapHistory } from '../modules/application/l1/l2/l3/map/mapCurrent/MapHistory';
import { MapRemoved } from '../modules/application/l1/l2/l3/map/mapCurrent/MapRemoved';
import { MapFile } from '../modules/application/l1/l2/l3/map/mapFile/MapFile';
import { MapObject } from '../modules/application/l1/l2/l3/map/mapObject/MapObject';
import { MapObjectCurrent } from '../modules/application/l1/l2/l3/map/mapObject/MapObjectCurrent';
import { MapObjectNew } from '../modules/application/l1/l2/l3/map/mapObject/MapObjectNew';
import { MapObjectParentNames } from '../modules/application/l1/l2/l3/map/mapObject/MapObjectParentNames';
import { MapObjectRelationRemoved } from '../modules/application/l1/l2/l3/map/mapObject/MapObjectRelationRemoved';
import { MapObjectRemoved } from '../modules/application/l1/l2/l3/map/mapObject/MapObjectRemoved';
import { MapObjectsLink } from '../modules/application/l1/l2/l3/map/mapObject/MapObjectsLink';
import { MapObjectUrl } from '../modules/application/l1/l2/l3/map/mapObject/MapObjectUrl';
import { ObjectsOutsideScreen } from '../modules/application/l1/l2/l3/map/mapObject/ObjectsOutsideScreen';
import { MapSettings } from '../modules/application/l1/l2/l3/map/mapSettings/MapSettings';
import { MapTypeCurrent } from '../modules/application/l1/l2/l3/map/mapTypes/MapTypeCurrent';
import { MapTypeNew } from '../modules/application/l1/l2/l3/map/mapTypes/MapTypeNew';
import { MapTypeRemoved } from '../modules/application/l1/l2/l3/map/mapTypes/MapTypeRemoved';
import { MapTypes } from '../modules/application/l1/l2/l3/map/mapTypes/MapTypes';
import { ParentTypes } from '../modules/application/l1/l2/l3/map/mapTypes/ParentTypes';
import { ObjectsMatchedToQuery } from '../modules/application/l1/l2/l3/search/ObjectsMatchedToQuery';
import { StageDefaultSize } from '../modules/application/l1/l2/l3/stage/StageDefaultSize';
import { MapObjectsVisible } from '../modules/application/l1/l2/l3/visibleObjects/MapObjectsVisible';
import { ObjectAdditionalFieldsFix } from '../modules/application/l1/l2/structuring/objectAdditionalFieldsFix/ObjectAdditionalFieldsFix';
import { MapObjectsArrows } from '../modules/application/l1/l2/visualisation/arrows/MapObjectsArrows';
import { NewArrow } from '../modules/application/l1/l2/visualisation/arrows/NewArrow';
import { MapObjectBackground } from '../modules/application/l1/l2/visualisation/background/MapObjectBackground';
import { Breadcrumbs } from '../modules/application/l1/l2/visualisation/breadcrumbs/Breadcrumbs';
import { Drawer } from '../modules/application/l1/l2/visualisation/drawer/Drawer';
import { Fps } from '../modules/application/l1/l2/visualisation/fps/Fps';
import { Menu } from '../modules/application/l1/l2/visualisation/menu/Menu';
import { MiniMap } from '../modules/application/l1/l2/visualisation/miniMap/MiniMap';
import { Modal } from '../modules/application/l1/l2/visualisation/modal/Modal';
import { Notification } from '../modules/application/l1/l2/visualisation/notification/Notification';
import { ObjectGeometryFix } from '../modules/application/l1/l2/visualisation/objectGeometryFix/ObjectGeometryFix';
import { MapObjectsRects } from '../modules/application/l1/l2/visualisation/rects/MapObjectsRects';
import { Resizing } from '../modules/application/l1/l2/visualisation/resizing/Resizing';
import { StagePosition } from '../modules/application/l1/l2/visualisation/stage/StagePosition';
import { StagePositionByObjectId } from '../modules/application/l1/l2/visualisation/stage/StagePositionByObjectId';
import { BrowserCanvas } from '../modules/integration/browser/canvas/BrowserCanvas';
import { ControlCombo } from '../modules/integration/browser/keyboard/ControlCombo';
import { Keyboard } from '../modules/integration/browser/keyboard/Keyboard';
import { KonvaLayer } from '../modules/integration/konva/KonvaLayer';
import { GuestAware } from 'patron-oop';
export declare const useApplication: () => {
    mapCurrentID: MapCurrentID;
    mapFile: MapFile;
    mapCurrent: MapCurrent;
    mapCurrentSource: GuestAware<MapDocument>;
    mapRemoved: MapRemoved;
    mapSettings: MapSettings;
    mapObject: MapObject;
    mapObjectRemoved: MapObjectRemoved;
    mapType: MapTypes;
    mapTypeRemoved: MapTypeRemoved;
    mapTypeNew: MapTypeNew;
    mapObjectsVisible: MapObjectsVisible;
    mapObjectCurrent: MapObjectCurrent;
    mapObjectNew: MapObjectNew;
    mapObjectsLink: MapObjectsLink;
    mapTypeCurrent: MapTypeCurrent;
    mapRects: MapObjectsRects;
    mapBackground: MapObjectBackground;
    mapObjectArrows: MapObjectsArrows;
    mapObjectsGeometryFix: ObjectGeometryFix;
    canvas: BrowserCanvas;
    miniMap: MiniMap;
    notification: Notification;
    modal: Modal;
    drawer: Drawer;
    konvaLayer: KonvaLayer;
    resizing: Resizing;
    objectAdditionalFieldsFix: ObjectAdditionalFieldsFix;
    mapObjectRelationRemoved: MapObjectRelationRemoved;
    fps: Fps;
    breadcrumbs: Breadcrumbs;
    mapObjectUrl: MapObjectUrl;
    keyboard: Keyboard;
    parentNames: MapObjectParentNames;
    parentTypes: ParentTypes;
    controlCombo: ControlCombo;
    menu: Menu;
    stagePosition: StagePosition;
    stagePositionByObjectId: StagePositionByObjectId;
    objectsMatchedToQuery: ObjectsMatchedToQuery;
    stageSize: StageDefaultSize;
    mapHistory: MapHistory;
    fileContent: import('patron-oop').Source<any>;
    newArrow: NewArrow;
    objectsOutsideScreen: ObjectsOutsideScreen;
};
